FROM keptnexamples/workshop-utils-base:0.5.0

######################################################################
# Amazon specific tools
# https://docs.aws.amazon.com/cli/latest/userguide/install-linux.html
######################################################################

# install python
RUN apt-get update -qq && \
  apt-get install -qqy --no-install-recommends \
    python3 \
    python3-distutils \
  && rm -rf /var/lib/apt/lists/*

# install pip
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py --user
ENV PATH ~/.local/bin:$PATH

## AWS CLI
RUN ~/.local/bin/pip3 install awscli --upgrade --user
RUN rm get-pip.py

## aws-iam-authenticator
ARG EKS_IAM_AUTHENTICATOR_VERSION=https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
RUN curl -o aws-iam-authenticator ${EKS_IAM_AUTHENTICATOR_VERSION}
RUN chmod +x ./aws-iam-authenticator
RUN mv aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

## eksctl - utility used to provison eks cluster
ARG EKS_EKSCTL_VERSION=latest_release
RUN curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/${EKS_EKSCTL_VERSION}/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C .
RUN mv eksctl /usr/local/bin/eksctl
RUN rm -rf eksctl*.tar.gz

# show versions
RUN ~/.local/bin/pip3 --version
RUN aws-iam-authenticator version
RUN eksctl version

