FROM keptnworkshops/workshop-utils-base:0.5.0

######################################################################
# Google specific tools
# https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu
######################################################################

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
RUN apt-get update \
  && apt-get install google-cloud-sdk -y --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*
RUN gcloud --version

