FROM keptnworkshops/workshop-utils-base:0.5.0

######################################################################
# Azure specific tools
# https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt
######################################################################
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
RUN az --version
